# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_oembed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oembedrichplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_oembed_oembedrichplugin', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='oembedvideoplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_oembed_oembedvideoplugin', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
